### ISSUE TITLE
Would you open source your code of the star map?

### ISSUE THREAD

**Issue by YogiWu** [RommelTJ/PurNKleen_Website#5]
It's so amazing effect of the star map on your website.I can't wait to study how to implement it.

**Comment by RommelTJ** [comment]
That's funny. I don't really have a Star Map on purnkleen.com. If I did, I would open source it. Do you mean the parallax effect with the Starfarer and Yela?

**Comment by YogiWu** [comment]
Sorry,I didn't make it claer.This is the link on your website.
https://robertsspaceindustries.com/starmap

**Comment by RommelTJ** [comment]
I see. You got me confused by a member of Cloud Imperium Games. I am not affiliated with them in any way, nor do I have access to the StarMap code. Closing.
